name: "Update flake"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * 1,4'

jobs:
  update_lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NIXPKGS_ALLOW_UNFREE: 1
      NIXPKGS_ALLOW_UNBROKEN: 1

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: install nix
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: update flake.lock
      run: nix flake update --accept-flake-config --impure

    - name: push flake.lock
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "update flake.lock"
        file_pattern: "flake.lock"
